-- =====================================================================
-- ADITI SUPER APP — JOB PORTAL DATABASE SCHEMA & SEED DATA
-- Target Database: Supabase PostgreSQL
-- All data is stored in the database directly (No frontend hardcoding)
-- =====================================================================

-- 1. Create job_vacancies table if not exists
CREATE TABLE IF NOT EXISTS public.job_vacancies (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  company_logo TEXT,
  category TEXT NOT NULL,
  subcategory TEXT,
  job_type TEXT NOT NULL,
  work_mode TEXT DEFAULT 'onsite',
  location TEXT NOT NULL,
  city TEXT NOT NULL,
  district TEXT,
  state TEXT DEFAULT 'Kerala',
  pincode TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  is_remote BOOLEAN DEFAULT FALSE,
  salary_min NUMERIC,
  salary_max NUMERIC,
  salary_period TEXT DEFAULT 'month',
  salary_formatted TEXT NOT NULL,
  experience_required TEXT NOT NULL,
  qualification_required TEXT NOT NULL,
  description TEXT NOT NULL,
  responsibilities JSONB DEFAULT '[]'::jsonb,
  skills JSONB DEFAULT '[]'::jsonb,
  contact_name TEXT NOT NULL,
  contact_phone TEXT,
  contact_email TEXT,
  contact_avatar TEXT,
  openings_count INTEGER DEFAULT 1,
  is_urgent BOOLEAN DEFAULT FALSE,
  is_featured BOOLEAN DEFAULT FALSE,
  is_verified BOOLEAN DEFAULT TRUE,
  application_count INTEGER DEFAULT 0,
  view_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active',
  is_saved BOOLEAN DEFAULT FALSE,
  posted_by_user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS & Realtime on job_vacancies
ALTER TABLE public.job_vacancies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on job_vacancies" 
ON public.job_vacancies FOR SELECT USING (true);

CREATE POLICY "Allow authenticated/public insert on job_vacancies" 
ON public.job_vacancies FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow update on job_vacancies" 
ON public.job_vacancies FOR UPDATE USING (true);

CREATE POLICY "Allow delete on job_vacancies" 
ON public.job_vacancies FOR DELETE USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.job_vacancies;

-- 2. Insert Infopark Kochi & Technopark TVM Vacancies directly into DB
INSERT INTO public.job_vacancies (
  id, title, company, category, subcategory, job_type, work_mode,
  location, city, district, state, pincode, latitude, longitude, is_remote,
  salary_min, salary_max, salary_period, salary_formatted, experience_required,
  qualification_required, description, responsibilities, skills, contact_name,
  contact_email, contact_avatar, openings_count, is_urgent, is_featured, is_verified,
  application_count, view_count, status, created_at
) VALUES 
-- INFOPARK KOCHI
(
  'job-infopark-1',
  'DevOps & Cloud Infrastructure Lead',
  'Thinkpalm Technologies Pvt. Ltd',
  'Technology & IT',
  'DevOps & Cloud',
  'Full-time',
  'hybrid',
  'Athulya Building, Infopark Phase 1, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0104,
  76.3639,
  FALSE,
  90000,
  150000,
  'month',
  '₹90,000 - ₹1,50,000 / mo',
  '5-8 Years',
  'B.Tech / BE / MCA in Computer Science or IT',
  'Lead enterprise cloud migration, CI/CD pipeline automation, containerization with Kubernetes/Docker, and Datadog/Prometheus monitoring for telecom and IoT products at Infopark Kochi.',
  '["Architect and maintain high-availability AWS and Azure architectures", "Manage CI/CD pipelines with GitHub Actions and GitLab CI", "Oversee multi-node Kubernetes clusters", "Implement zero-trust security and cost optimization"]'::jsonb,
  '["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform", "Datadog", "Linux RHEL"]'::jsonb,
  'HR Talent Team',
  'careers@thinkpalm.com',
  'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  3,
  TRUE,
  TRUE,
  TRUE,
  14,
  280,
  'active',
  NOW()
),
(
  'job-infopark-2',
  'Senior Frontend Engineer (React & TypeScript)',
  'Tecforz Innovations Pvt Ltd',
  'Technology & IT',
  'Frontend Engineering',
  'Full-time',
  'hybrid',
  'Carnival Infopark, Phase 2, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0125,
  76.3685,
  TRUE,
  80000,
  130000,
  'month',
  '₹80,000 - ₹1,30,000 / mo',
  '4-7 Years',
  'B.Tech / BCA / MCA / B.Sc Computer Science',
  'Design and engineer mission-critical, high-performance web applications using React 18, TypeScript, TailwindCSS, and Next.js for global fintech and SaaS clients.',
  '["Develop pixel-perfect UI components with Tailwind CSS & Shadcn/UI", "Optimize web vitals, Zustand state management, and GraphQL client caching", "Write robust unit tests using Vitest and React Testing Library"]'::jsonb,
  '["React", "TypeScript", "Next.js", "TailwindCSS", "GraphQL", "Redux Toolkit", "Vitest"]'::jsonb,
  'Talent Acquisition Team',
  'hr@tecforz.com',
  'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
  2,
  TRUE,
  TRUE,
  TRUE,
  19,
  310,
  'active',
  NOW()
),
(
  'job-infopark-3',
  'Flutter & Cross-Platform Mobile Engineer',
  'Panasa Technology',
  'Technology & IT',
  'Mobile App Development',
  'Full-time',
  'onsite',
  'Thapasya Building, Infopark Phase 1, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0118,
  76.3622,
  FALSE,
  45000,
  70000,
  'month',
  '₹45,000 - ₹70,000 / mo',
  '2-4 Years',
  'B.Tech / BCA / MCA',
  'Build native-feel iOS and Android consumer mobile applications using Flutter & Dart. Integrate with RESTful microservices, push notifications, and payment gateways.',
  '["Build reusable Flutter UI components with Bloc or Riverpod architecture", "Integrate Firebase Cloud Messaging, Razorpay/Stripe, and offline SQLite synchronization", "Manage end-to-end Google Play Console and Apple App Store deployment pipelines"]'::jsonb,
  '["Flutter", "Dart", "Bloc", "REST APIs", "Firebase", "App Store Deployment"]'::jsonb,
  'HR Operations',
  'careers@panasatech.com',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
  2,
  FALSE,
  TRUE,
  TRUE,
  8,
  165,
  'active',
  NOW()
),
(
  'job-infopark-4',
  'Lead Generative AI & Machine Learning Engineer',
  'Experion Technologies',
  'Technology & IT',
  'Artificial Intelligence & Data Science',
  'Full-time',
  'hybrid',
  'Vismaya Building, Infopark Phase 1, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0131,
  76.3644,
  TRUE,
  110000,
  180000,
  'month',
  '₹1,10,000 - ₹1,80,000 / mo (₹14 - ₹22 LPA)',
  '4-8 Years',
  'B.Tech / M.Tech in Computer Science / AI & ML',
  'Design generative AI agents, LLM orchestration pipelines (LangChain/LlamaIndex), RAG systems with vector databases, and fine-tune open-weight models for enterprise automation.',
  '["Develop Retrieval-Augmented Generation (RAG) applications using Pinecone and ChromaDB", "Build multi-agent AI workflows and evaluate LLM responses using benchmark suites", "Deploy low-latency AI inference endpoints on AWS SageMaker and GCP Vertex AI"]'::jsonb,
  '["Python", "LangChain", "LlamaIndex", "Vector Databases", "PyTorch", "FastAPI", "AWS SageMaker"]'::jsonb,
  'Engineering Talent Team',
  'talent@experionglobal.com',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  3,
  TRUE,
  TRUE,
  TRUE,
  22,
  420,
  'active',
  NOW()
),
(
  'job-infopark-5',
  'Full Stack .NET Core & Angular Engineer',
  'AlignMinds Technologies',
  'Technology & IT',
  'Enterprise Software',
  'Full-time',
  'hybrid',
  'Lulu Cyber Tower 2, Infopark Phase 2, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0152,
  76.3712,
  FALSE,
  55000,
  85000,
  'month',
  '₹55,000 - ₹85,000 / mo',
  '3-5 Years',
  'B.Tech / MCA / M.Sc Computer Science',
  'Build robust enterprise microservices using C#, ASP.NET Core Web API, Entity Framework, PostgreSQL/SQL Server, paired with reactive Angular 17+ frontends.',
  '["Develop modular ASP.NET Core REST APIs with clean architecture and CQRS patterns", "Implement responsive Angular standalone components with RxJS state streams", "Write automated integration tests and optimize database query plans"]'::jsonb,
  '["C#", ".NET Core", "Angular", "SQL Server", "Entity Framework", "Azure", "Microservices"]'::jsonb,
  'Talent Acquisition Team',
  'careers@alignminds.com',
  'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150',
  4,
  FALSE,
  TRUE,
  TRUE,
  11,
  210,
  'active',
  NOW()
),
(
  'job-infopark-6',
  'Performance Marketing & Growth Specialist',
  'Inspite Technologies Pvt. Ltd',
  'Sales & Marketing',
  'Digital Growth & Ads',
  'Full-time',
  'onsite',
  'Infopark Phase 1, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0108,
  76.3631,
  FALSE,
  35000,
  55000,
  'month',
  '₹35,000 - ₹55,000 / mo + Bonus',
  '2-4 Years',
  'Any Graduate / BBA / MBA in Marketing',
  'Drive multi-channel digital performance marketing campaigns across Meta Ads, Google Search & Display, LinkedIn Ads, and conversion rate optimization (CRO) for international B2B SaaS accounts.',
  '["Manage $50k+ monthly ad spend across Google Ads and Meta Ads Manager", "Run rigorous A/B experiments on landing pages and ad copy to lower CAC", "Analyze funnel analytics using GA4, Mixpanel, and Google Tag Manager"]'::jsonb,
  '["Google Ads", "Meta Ads", "SEO", "GA4 Analytics", "Conversion Rate Optimization", "Copywriting"]'::jsonb,
  'Growth Hiring Desk',
  'jobs@inspitetech.com',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  2,
  TRUE,
  TRUE,
  TRUE,
  16,
  295,
  'active',
  NOW()
),
(
  'job-infopark-7',
  'Customer Experience & International Tech Support Associate',
  'Speridian Technologies Pvt Ltd',
  'Technology & IT',
  'Customer Support & Client Ops',
  'Full-time',
  'onsite',
  'Infopark Phase 1, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0112,
  76.3635,
  FALSE,
  28000,
  40000,
  'month',
  '₹28,000 - ₹40,000 / mo + Shift Allowance',
  '0-2 Years (Freshers Welcome)',
  'Any Degree (B.Tech / B.Sc / BCA / B.Com / BA)',
  'Provide tier-1 and tier-2 technical resolution, CRM ticket handling, and omnichannel customer communication (email, chat, phone) for North American enterprise clients.',
  '["Troubleshoot software application issues and escalate complex bugs with detailed steps", "Maintain >95% CSAT score and SLA thresholds", "Document knowledge base articles and troubleshooting workflows"]'::jsonb,
  '["English Communication", "Technical Support", "CRM Ticketing", "ITIL", "Problem Solving"]'::jsonb,
  'HR Sourcing Team',
  'careers.kochi@speridian.com',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  8,
  TRUE,
  FALSE,
  TRUE,
  35,
  520,
  'active',
  NOW()
),
(
  'job-infopark-8',
  'IT Talent Acquisition & HR Executive',
  'Inspite Technologies Pvt. Ltd',
  'Technology & IT',
  'Human Resources',
  'Full-time',
  'onsite',
  'Infopark Phase 1, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0108,
  76.3631,
  FALSE,
  25000,
  42000,
  'month',
  '₹25,000 - ₹42,000 / mo',
  '1-3 Years',
  'MBA HR / MHRM / MSW / BBA',
  'Manage full recruitment lifecycle for software developers, QA engineers, and cloud architects. Conduct preliminary HR rounds, coordinate technical evaluations, and manage onboarding.',
  '["Source tech talent via LinkedIn Recruiter, Naukri, and developer communities", "Conduct initial screening interviews and salary negotiations", "Drive employee engagement programs and performance appraisal cycles"]'::jsonb,
  '["Technical Recruiting", "LinkedIn Sourcing", "HR Operations", "Employee Onboarding", "Payroll"]'::jsonb,
  'HR Recruitment Desk',
  'hr@inspitetech.com',
  'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  2,
  TRUE,
  FALSE,
  TRUE,
  12,
  240,
  'active',
  NOW()
),
(
  'job-infopark-9',
  'Senior QA Automation Engineer (Playwright / Cypress)',
  'Grapelime Innovations Private Limited',
  'Technology & IT',
  'Quality Assurance',
  'Full-time',
  'hybrid',
  'Infopark Phase 2, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0142,
  76.3698,
  TRUE,
  60000,
  90000,
  'month',
  '₹60,000 - ₹90,000 / mo',
  '3-6 Years',
  'B.Tech / BCA / MCA in Computer Science',
  'Design and execute robust automated end-to-end and API testing suites using Playwright, Cypress, TypeScript, and Postman. Integrate test runs into CI/CD build gates.',
  '["Author scalable test automation frameworks in TypeScript with Playwright", "Execute REST and GraphQL API contract and security testing", "Perform load and stress testing using k6 / JMeter"]'::jsonb,
  '["Playwright", "Cypress", "TypeScript", "Postman API Testing", "CI/CD Pipelines", "k6 Load Testing"]'::jsonb,
  'QA Engineering Desk',
  'careers@grapelime.in',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
  3,
  FALSE,
  TRUE,
  TRUE,
  15,
  290,
  'active',
  NOW()
),
(
  'job-infopark-10',
  'Cloud Data Center & Network Security Lead',
  'Penguin Data Centre Pvt. Ltd',
  'Technology & IT',
  'IT Infrastructure & Security',
  'Full-time',
  'onsite',
  'Infopark Phase 1, Kakkanad',
  'Kochi',
  'Ernakulam',
  'Kerala',
  '682042',
  10.0105,
  76.3640,
  FALSE,
  75000,
  115000,
  'month',
  '₹75,000 - ₹1,15,000 / mo',
  '5-9 Years',
  'B.Tech / BE Electronics / CS with CCNA / CCNP / CISSP',
  'Manage mission-critical data center network infrastructure, Fortinet/Palo Alto enterprise firewalls, SAN/NAS storage arrays, and ISO 27001 cybersecurity compliance at Infopark Kochi.',
  '["Configure Cisco BGP routing, VLANs, spine-leaf switching, and VPN tunnels", "Manage next-gen enterprise firewalls and intrusion prevention systems", "Conduct regular vulnerability assessments and incident response drills"]'::jsonb,
  '["Cisco Routing & Switching", "Fortinet Firewalls", "Linux Server Admin", "Network Security", "ISO 27001"]'::jsonb,
  'Infrastructure HR Desk',
  'noc.careers@penguindc.com',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
  2,
  TRUE,
  TRUE,
  TRUE,
  9,
  180,
  'active',
  NOW()
),

-- TECHNOPARK TRIVANDRUM
(
  'job-technopark-1',
  'Senior Cloud Solutions Architect & Spring Boot Lead',
  'UST (UST Global)',
  'Technology & IT',
  'Cloud & Enterprise Architecture',
  'Full-time',
  'hybrid',
  'UST Campus, Technopark Phase 2, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5568,
  76.8820,
  FALSE,
  120000,
  200000,
  'month',
  '₹1,20,000 - ₹2,00,000 / mo (₹15 - ₹25 LPA)',
  '6-10 Years',
  'B.Tech / MCA in Computer Science / IT',
  'Lead digital transformation and cloud modernization for Fortune 500 healthcare and retail clients. Architect event-driven microservices on AWS/GCP with Spring Boot 3, Kafka, and Kubernetes.',
  '["Architect high-throughput event-driven microservices using Spring Boot 3 & Kafka", "Lead cloud migration roadmaps across multi-cloud environments (AWS & Azure)", "Mentor engineering teams in domain-driven design, CI/CD automation, and zero-downtime deployments"]'::jsonb,
  '["Java 21", "Spring Boot", "AWS", "Kubernetes", "Kafka", "Microservices", "PostgreSQL"]'::jsonb,
  'UST Talent Acquisition',
  'careers@ust.com',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  5,
  TRUE,
  TRUE,
  TRUE,
  28,
  450,
  'active',
  NOW()
),
(
  'job-technopark-2',
  'Aviation & Airline SaaS Product Engineer (Python & Microservices)',
  'IBS Software Pvt Ltd',
  'Technology & IT',
  'Software Engineering',
  'Full-time',
  'hybrid',
  'Nila Building, Technopark Phase 1, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5582,
  76.8809,
  FALSE,
  85000,
  140000,
  'month',
  '₹85,000 - ₹1,40,000 / mo',
  '4-7 Years',
  'B.Tech / BE in CS, IT, or Electronics',
  'Build next-generation SaaS flight operations, airline cargo management, and passenger service systems powering top global airline alliances.',
  '["Develop scalable REST & gRPC microservices with Python, FastAPI, and Go", "Optimize complex relational and document database pipelines for flight schedule routing", "Collaborate with international airline domain architects on product enhancements"]'::jsonb,
  '["Python", "FastAPI", "Microservices", "PostgreSQL", "Docker", "Redis", "Kafka"]'::jsonb,
  'IBS Talent Team',
  'careers@ibsplc.com',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  4,
  TRUE,
  TRUE,
  TRUE,
  21,
  380,
  'active',
  NOW()
),
(
  'job-technopark-3',
  'Automotive Embedded Systems & AUTOSAR Software Engineer',
  'Tata Elxsi Limited',
  'Technology & IT',
  'Embedded & Automotive Systems',
  'Full-time',
  'onsite',
  'Neyyar Building, Technopark Phase 1, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5574,
  76.8815,
  FALSE,
  70000,
  120000,
  'month',
  '₹70,000 - ₹1,20,000 / mo',
  '3-6 Years',
  'B.Tech in Electronics / Electrical / Computer Science',
  'Develop safety-critical automotive software for Electric Vehicles (EV) and Autonomous Driving systems conforming to ISO 26262 ASIL standards.',
  '["Develop Classic/Adaptive AUTOSAR BSW modules and MCAL device drivers in Embedded C", "Implement CAN, LIN, and Automotive Ethernet communication protocol stacks", "Perform Hardware-in-the-Loop (HIL) and SIL testing with Vector CANoe"]'::jsonb,
  '["Embedded C", "AUTOSAR", "CAN / LIN", "Vector CANoe", "ISO 26262", "RTOS", "Microcontrollers"]'::jsonb,
  'Tata Elxsi HR Team',
  'careers@tataelxsi.com',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  6,
  TRUE,
  TRUE,
  TRUE,
  18,
  310,
  'active',
  NOW()
),
(
  'job-technopark-4',
  'Senior Full Stack Engineer (Java 21 & React)',
  'Allianz Technology India',
  'Technology & IT',
  'Full Stack Development',
  'Full-time',
  'hybrid',
  'Ganga Building, Technopark Phase 3, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5492,
  76.8901,
  TRUE,
  95000,
  155000,
  'month',
  '₹95,000 - ₹1,55,000 / mo',
  '5-8 Years',
  'B.Tech / MCA / B.Sc CS',
  'Architect global insurance and financial technology applications serving millions of European customers with high availability and stringent GDPR compliance.',
  '["Develop modern web applications using React 18, TypeScript, and Java 21 Spring Boot", "Implement OAuth2 / OpenID Connect security flows and Azure AD integration", "Design unit and automated end-to-end test suites ensuring 90%+ code coverage"]'::jsonb,
  '["Java 21", "Spring Boot", "React", "TypeScript", "PostgreSQL", "Docker", "Azure"]'::jsonb,
  'Allianz Recruitment Desk',
  'careers.india@allianz.com',
  'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  3,
  FALSE,
  TRUE,
  TRUE,
  15,
  275,
  'active',
  NOW()
),
(
  'job-technopark-5',
  'Lead Big Data & Real-Time Analytics Engineer',
  'SunTec Business Solutions',
  'Technology & IT',
  'Data Engineering',
  'Full-time',
  'hybrid',
  'SunTec Tower, Technopark Phase 3, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5485,
  76.8895,
  FALSE,
  100000,
  165000,
  'month',
  '₹1,00,000 - ₹1,65,000 / mo',
  '5-9 Years',
  'B.Tech / M.Tech in CS / Data Science',
  'Lead real-time pricing and billing data pipelines processing billions of financial transactions daily for Tier-1 international banks.',
  '["Build high-performance streaming pipelines using Apache Spark, Kafka, and Flink", "Optimize data warehousing and lakehouse architectures with Snowflake and Databricks", "Implement automated data quality monitoring and anomaly detection triggers"]'::jsonb,
  '["Apache Spark", "Kafka", "Scala / Python", "Snowflake", "PostgreSQL", "Airflow"]'::jsonb,
  'SunTec Talent Acquisition',
  'careers@suntecgroup.com',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
  2,
  TRUE,
  TRUE,
  TRUE,
  13,
  220,
  'active',
  NOW()
),
(
  'job-technopark-6',
  'Senior Financial Data & AI Systems Engineer',
  'Envestnet India',
  'Technology & IT',
  'FinTech & Data Science',
  'Full-time',
  'hybrid',
  'Thejaswini Building, Technopark Phase 1, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5590,
  76.8825,
  TRUE,
  90000,
  145000,
  'month',
  '₹90,000 - ₹1,45,000 / mo',
  '4-7 Years',
  'B.Tech / MCA / M.Sc Data Science',
  'Design wealth management intelligence systems and automated financial advisory engines for the US wealth management market.',
  '["Develop portfolio optimization and investment risk calculation algorithms in Python and C#", "Integrate with market data feeds (NYSE, NASDAQ) with sub-second latency", "Deploy machine learning models for asset allocation recommendations"]'::jsonb,
  '["Python", "C# .NET", "SQL Server", "AWS", "Pandas", "Machine Learning", "FinTech"]'::jsonb,
  'Envestnet HR Team',
  'india.careers@envestnet.com',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
  3,
  FALSE,
  TRUE,
  TRUE,
  17,
  290,
  'active',
  NOW()
),
(
  'job-technopark-7',
  'Senior React Native Mobile Architect',
  'QBurst Technologies Pvt. Ltd',
  'Technology & IT',
  'Mobile App Engineering',
  'Full-time',
  'hybrid',
  'Technopark Phase 1, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5578,
  76.8812,
  TRUE,
  75000,
  120000,
  'month',
  '₹75,000 - ₹1,20,000 / mo',
  '4-7 Years',
  'B.Tech / BCA / MCA',
  'Architect high-performance cross-platform iOS and Android mobile apps with React Native, TypeScript, Redux Toolkit, and native bridge modules for international healthcare and e-commerce clients.',
  '["Architect scalable React Native applications with clean architecture and atomic design", "Build custom native Swift and Kotlin bridge modules for Bluetooth and sensors", "Implement smooth 60fps animations and optimize memory footprints"]'::jsonb,
  '["React Native", "TypeScript", "Redux Toolkit", "iOS Swift", "Android Kotlin", "GraphQL"]'::jsonb,
  'QBurst Recruitment Desk',
  'careers@qburst.com',
  'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
  4,
  TRUE,
  TRUE,
  TRUE,
  24,
  360,
  'active',
  NOW()
),
(
  'job-technopark-8',
  'Aerospace & Mechanical Design Specialist (CAD / FEA)',
  'Quest Global Technologies',
  'Technology & IT',
  'Mechanical & Aerospace Engineering',
  'Full-time',
  'onsite',
  'Amstor Building, Technopark Phase 1, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5585,
  76.8818,
  FALSE,
  65000,
  105000,
  'month',
  '₹65,000 - ₹1,05,000 / mo',
  '3-6 Years',
  'B.Tech / M.Tech in Mechanical / Aerospace Engineering',
  'Perform 3D CAD modeling, GD&T analysis, finite element analysis (FEA), and structural stress verification for global commercial aircraft and turbomachinery systems.',
  '["Create complex 3D parametric models and assembly drawings in CATIA V5 and Siemens NX", "Perform linear/nonlinear structural and thermal FEA simulations using ANSYS", "Coordinate design modifications with European and US aerospace OEM teams"]'::jsonb,
  '["CATIA V5", "Siemens NX", "ANSYS", "FEA Simulation", "GD&T", "Aerospace Structures"]'::jsonb,
  'Quest Global HR Desk',
  'careers@quest-global.com',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
  3,
  FALSE,
  FALSE,
  TRUE,
  10,
  195,
  'active',
  NOW()
),
(
  'job-technopark-9',
  'Cybersecurity SOC Analyst & Incident Response Lead',
  'Nissan Digital Hub India',
  'Technology & IT',
  'Cybersecurity & SOC',
  'Full-time',
  'hybrid',
  'Yamuna Building, Technopark Phase 3, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5490,
  76.8905,
  FALSE,
  80000,
  130000,
  'month',
  '₹80,000 - ₹1,30,000 / mo',
  '3-6 Years',
  'B.Tech in CS / IT / Cyber Security with CEH / CySA+ / CISSP',
  'Protect global connected vehicle telematics infrastructure, cloud workloads, and manufacturing plants from advanced persistent threats (APT) in a 24/7 Security Operations Center.',
  '["Monitor real-time SIEM alerts (Splunk, Microsoft Sentinel) and investigate anomalies", "Lead threat hunting and digital forensics incident response (DFIR) procedures", "Automate security playbooks using SOAR frameworks"]'::jsonb,
  '["SIEM", "Splunk", "Threat Hunting", "Incident Response", "Cloud Security", "MITRE ATT&CK"]'::jsonb,
  'Nissan Digital Talent Team',
  'careers@nissandigital.com',
  'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150',
  2,
  TRUE,
  TRUE,
  TRUE,
  14,
  260,
  'active',
  NOW()
),
(
  'job-technopark-10',
  'SAP S/4HANA Finance & Controlling (FICO) Senior Consultant',
  'Tata Consultancy Services (TCS)',
  'Technology & IT',
  'Enterprise ERP',
  'Full-time',
  'hybrid',
  'Peepul Park, Technopark Campus, Kazhakkoottam',
  'Thiruvananthapuram',
  'Thiruvananthapuram',
  'Kerala',
  '695581',
  8.5601,
  76.8790,
  FALSE,
  85000,
  140000,
  'month',
  '₹85,000 - ₹1,40,000 / mo',
  '5-8 Years',
  'B.Tech / MBA Finance / CA / ICWA / M.Com',
  'Lead end-to-end SAP S/4HANA financial transformation projects for multinational conglomerates. Configure General Ledger (GL), Accounts Payable/Receivable, Asset Accounting, and Product Costing.',
  '["Lead business blueprint workshops and configure SAP S/4HANA Finance modules", "Integrate SAP FICO with SD, MM, and external banking interfaces", "Drive data migration, cutover management, and post-go-live support"]'::jsonb,
  '["SAP S/4HANA", "SAP FICO", "General Ledger", "Product Costing", "Financial Accounting", "Integration"]'::jsonb,
  'TCS Talent Acquisition',
  'careers.india@tcs.com',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  5,
  FALSE,
  TRUE,
  TRUE,
  31,
  480,
  'active',
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  company = EXCLUDED.company,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  job_type = EXCLUDED.job_type,
  work_mode = EXCLUDED.work_mode,
  location = EXCLUDED.location,
  city = EXCLUDED.city,
  district = EXCLUDED.district,
  pincode = EXCLUDED.pincode,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  salary_min = EXCLUDED.salary_min,
  salary_max = EXCLUDED.salary_max,
  salary_formatted = EXCLUDED.salary_formatted,
  experience_required = EXCLUDED.experience_required,
  qualification_required = EXCLUDED.qualification_required,
  description = EXCLUDED.description,
  responsibilities = EXCLUDED.responsibilities,
  skills = EXCLUDED.skills,
  contact_name = EXCLUDED.contact_name,
  contact_email = EXCLUDED.contact_email,
  openings_count = EXCLUDED.openings_count,
  status = EXCLUDED.status,
  updated_at = NOW();
